# We create a PVC only if requested.
{{- if .Values.pvc.enabled }}{{- if .Values.pvc.create }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvc.name }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.temporaryStorageSize }}
  {{- if .Values.pvc.storageClassName }}
  {{- if (eq "-" .Values.pvc.storageClassName) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.pvc.storageClassName }}"
  {{- end }}
  {{- end }}
{{- end }}{{- end }}
